apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: pcola-me-tls
spec:
  secretName: pcola-me
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: pcola.me
  dnsNames:
    - www.pcola.me
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - www.pcola.me
          

